### ISSUE TITLE
Javascript, Jquery Functions, Onclick

### ISSUE THREAD

**Issue by joscarparo** [mgks/Android-SmartWebView#10]
Hi
i would like to thank you so much for the great job and share with us.

My the app is a mobile responsive website, but when i opened inside the project, my jquery and javascript functions stops.
The variable to enable the javascrit is true, but still not working. Do you have idea what can be?
Thank you very much!

**Comment by joscarparo** [comment]
Hi
Problem solved.
ASWP_OFFLINE = false;
Sorry for the inconvenience.
Tks

**Comment by mgks** [comment]
no problem!
I just read it but you've already solved the issue, that's great :)

**Comment by InspiredPrynce** [comment]
same issue am going through
have set  ASWP_OFFLINE = false; still not working
please help me out
