### ISSUE TITLE
The Smartphone Zoom Affects elements of WebView

### ISSUE THREAD

**Issue by jonnathanlopes** [mgks/Android-SmartWebView#100]
The zoom on smartphone affects the text elements in WebView. How can I avoid this? is there a setting to prevent the smartphone zoom from being applied to WebView?

![emulator](https://user-images.githubusercontent.com/26045692/61247452-7fba7500-a727-11e9-856b-2c6138e65876.PNG)

![Screenshot_2019-07-15-17-26-04-411_mgks os webview (1)](https://user-images.githubusercontent.com/26045692/61247653-dcb62b00-a727-11e9-8a45-8b1da66f8c6e.png)

**Comment by mgks** [comment]
there's a config variable called, `ASWP_ZOOM` in `SmartWebView.java`. You can try disabling it (by default it's already set to `false`) but if that's not the case, please try to elaborate the issue.

**Comment by jonnathanlopes** [comment]
Thanks for your Feedback but already tried this. I need to avoid that the system font-size, effects the android application. if i change the size of system the text in the webview (site informations) also change , i need this not occur.

**Comment by mgks** [comment]
you can't control that, it's part of system's viewing aid. It will vary from device to device, what you can do instead is change your font-size unit (from `px` to `em` or whatever suits your condition) that can handle screen size change.

**Comment by jonnathanlopes** [comment]
How Can i use   settings.setTextZoom(100 ) ?
