### ISSUE TITLE
can only use m. prefix to load site

### ISSUE THREAD

**Issue by HerbWalsh** [mgks/Android-SmartWebView#101]
I can only use m.domain.com to load app but because there are other prefix's in the site it won't allow to load those pages. is there any way I could just load domain.com and have the app allow domain.com or www.domain.com to load? ..or even load m.domain.com but allow domain.com or www.domain.com to load as well

**Comment by mgks** [comment]
Similar to Issue #62, you can find the [solution here](https://github.com/mgks/Android-SmartWebView/issues/62#issuecomment-446328993).
closing this one.

**Comment by HerbWalsh** [comment]
That does not answer my dilemma as I wish to use domain.com or www.domain.com for my host url so I don't have to have a sub domain set up and it won't let me, it only allows me to use m.domain.com but in another app it does allow domain.com..any ideas?

**Comment by timhj** [comment]
The linked ticket shows you how to add as many domains as you want to the
list of which domains to open in your app.

**Comment by HerbWalsh** [comment]
ok than I will have to see if i can figure it out

**Comment by HerbWalsh** [comment]
I have tried and it loads if i set my host url to m.domain.com but won't load the set exturls mydomain.com or www.domain.com and if my host url is mydomain.com it simply won't load at all. here is what I have done with mydomain.com set as host. please let me know if i have something wrong:
		 	//Opening external URLs in android default web browser
		} else if (ASWP_EXTURL && !aswm_host(url).equals(ASWV_HOST) && !aswm_host(url).equals("m.mydomain.com") && !aswm_host(url).equals("www.mydomain.com")){
			aswm_view(url,true);
		} else {
			a = false;
		}
		return a;
         }

**Comment by mgks** [comment]
does any of these domains have SSL encryption?

**Comment by HerbWalsh** [comment]
yes they do but one of my apps that I use with your project works as domain.com although that is the only host on that site ..the other one giving me trouble uses domain2.com and www.domain2.com and I have set up a m.domain2.com to try and accommodate it but nothing seems to work other than it loads if host is m.domain.com ..I will say I don't know why as I am not redirecting but in my facebook ads devices less than 1000px wide go to m.domain.com and those wider go to www.domain.com as I have set in my ad profile. I have no idea why as cloudfare has no such rules and my html pages have no links to s redirect script

**Comment by HerbWalsh** [comment]
I solved the redirect issue and host will now load as domain.com but won't load www.domain.com links..I can take out all www prefix in my site but as I said the other webview I am using has no issues with either

**Comment by mgks** [comment]
you had no need to make these changes and all could work fine but I'm getting a hint that you're not able to understand what we're trying to explain to you. Anyway, I'm glad you've got a fix.
