### ISSUE TITLE
Unable to scroll!

### ISSUE THREAD

**Issue by nathanm95** [mgks/Android-SmartWebView#102]
Hi,

I have made little changes to the base code but have run into a scrolling issue. On an emulator (Pixel 2) the app will scroll vertically as expected. Although when running on my physical samsung s7 i cant seem to scroll. Not sure whats happened as it used to work.

Has anyone got any ideas. I think the last thing i changed was turning off pull to refresh.

**Comment by mgks** [comment]
so you removed the code instead of just disabling it?

**Comment by nathanm95** [comment]
> so you removed the code instead of just disabling it?

I have set it to false

**Comment by mgks** [comment]
can you explain what changes you made to the base code?

**Comment by nathanm95** [comment]
> can you explain what changes you made to the base code?

I havent messed around with this app in months but i dont think ive changed all that much bar adding icons, changed url for webview, disabled splashscreen and changed the fonts and colors.

Maybe i have changed something else that has caused the issue. Would you have an idea of what i could of possible done?

**Comment by mgks** [comment]
I believe you should update your repo with the latest release, there was once an issue regarding pull to refresh and was resolved later. there is a chance you might be using an older variant.

**Comment by nathanm95** [comment]
> I believe you should update your repo with the latest release, there was once an issue regarding pull to refresh and was resolved later. there is a chance you might be using an older variant.

Ok thanks i will redownload and try again

**Comment by nathanm95** [comment]
Apologies i believe that its my website that maybe the problem as i have used a different url to a public website like youtube for example and it scrolls.

**Comment by nathanm95** [comment]
Apologies i believe that its my website that maybe the problem as i have used a different url to a public website like youtube for example and it scrolls.
