### ISSUE TITLE
HELLO i wanted to create an WebView for my ecommerce website with all possible features you can recommend.

### ISSUE THREAD

**Issue by Rohit6963** [mgks/Android-SmartWebView#103]
Hello,
I wanted a WebView Android app for my e-commerce website.
I need some features onto it like
1. Splash screen loading till the websites loads in the background (only at the start)
2. I want File Upload feature in my webview app
3. need permission to redirect to third party apps like Whatsapp, Facebook, Email for quick chat feature.
4. And also the colour adaptive notification bar
5. I am also getting a suggestion in ANDROID STUDIO (to add at least one Activity with an ACTION-VIEW intent filter or my app will not be indexable by google)

Please Help me out with this.

Here are my codes

**AndroidManifest.xml**

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    android:name="android.support.multidex.MultiDexApplication"
    package="com.clothing.vehopmain">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:screenOrientation="portrait"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true">
        <activity android:name=".SplashActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".MainActivity"
            android:screenOrientation="portrait"></activity>

    </application>

</manifest>

**MainActivity.java**

package com.clothing.vehopmain;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;

import java.util.Timer;
import java.util.TimerTask;

public class MainActivity extends AppCompatActivity {
    private boolean exit=false;
    private WebView webView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        webView =(WebView)findViewById(R.id.webview);
        webView.loadUrl("https://www.vehop.in/");
        WebSettings webSettings= webView.getSettings();
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setWebChromeClient(new WebChromeClient());
        webView.setWebViewClient(new WebViewClient());
    }

    @Override
    public void onBackPressed() {
        if (webView.canGoBack()) {
            webView.goBack();
        }
        else
        {
            //super.onBackPressed();

            if (exit)
            {
                finish();
            }
            else
            {
                Toast.makeText(MainActivity.this,"press again to exit..", Toast.LENGTH_SHORT).show();
            }
            Timer timer=new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    exit=false;

                }
            },2000);
            exit=true;
        }
    }}

**SplashActivity.java**

package com.clothing.vehopmain;

import android.content.Intent;
import android.os.Handler;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class SplashActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                Intent intent = new Intent(SplashActivity.this, MainActivity.class);
                startActivity (intent);
                finish();
            }
        },1500);
    }
}

**activity_main.xml**

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.clothing.vehopmain.MainActivity">

    <WebView
        android:id="@+id/webview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>

**activity_splash.xml**

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background"
    tools:context=".SplashActivity">

    <ProgressBar
        android:id="@+id/progress_bar"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true" />

</RelativeLayout>

**Comment by mgks** [comment]
Hey,

I looked into the codes you mentioned and idk where you got it from, it's all basic webview structure, not Smart WebView. I suggest you download SWV; it will be a lot easier for you to customize without getting into the main files.

**Comment by mgks** [comment]
**For loading screen,**
1. Add `loading_view` in `activity_main` layout before webview component. You can add images and more components within the `loading_view` layout to make it more interactive.
```
<RelativeLayout
    android:id="@+id/loading_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:visibility="visible"
    android:gravity="center_vertical|center_horizontal|center"
    android:layout_alignParentTop="true"
    android:layout_alignParentLeft="true"
    android:layout_alignParentStart="true"
    tools:ignore="RtlHardcoded">
    <TextView
        android:id="@+id/loading_text"
        android:layout_height="wrap_content"
        android:gravity="center_vertical|center_horizontal|center"
        android:layout_width="match_parent"
        android:text="Loading app..."
        android:textSize="18sp"
        android:textStyle="normal|bold"
        android:textColor="?android:attr/textColorTertiary"
        android:layout_marginTop="26dp"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true" />
</RelativeLayout>
```
2. Update `activity_main`, add `android:visibility="gone"` to `webview` component.

3. Add callback method to `MainActivity`, with `onPageFinished` we'll know when page finishes loading: it will hide `loading_view` and make `webview` visible.
```
private class Callback extends WebViewClient {
    public void onPageFinished(WebView view, String url) {
        findViewById(R.id.loading_view).setVisibility(View.GONE);
        findViewById(R.id.webview).setVisibility(View.VISIBLE);
    }
}
```

Regarding your other feature request, I still suggest you to start using SWV as some of your required features are already there and other will come along updates. Try it.

**Comment by Rohit6963** [comment]
I tried placing these codes but no difference... I still get the same white screen in between.
can our place those codes into my codes and then it here?

**Comment by mgks** [comment]
can you upload your source code in your github profile? I'll check it from there and update it after testing, that will be easier for you understand and atleast your app will work accordingly.

To get started just watch any tutorial on creating a new repo on github.
