### ISSUE TITLE
Record audio ?

### ISSUE THREAD

**Issue by aktiwers** [mgks/Android-SmartWebView#104]
Hi mgks, 
Thanks for making this PWA project!

I was wondering if there is any way to record Audio using:
`<input type="file" accept="audio/*" capture>` 

Do I have to bundle my own audio recorder app into the project or is there another way?

Thanks in advance

**Comment by mgks** [comment]
There's nothing integrated for audio recording in the project at the moment. Maybe you can help us with that :)

**Comment by aktiwers** [comment]
Alright, I ended up switching my project to React-native. But I will be happy to help with this when I get time.
