### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by nikolas27** [mgks/Android-SmartWebView#105]
Hello, when i try to upload on Google play, i get this error message:

You need to use a different package name because "mgks.os.webview" already exists in Google Play.

How can i fix this?
Thanks a lot in advance

**Comment by nikolas27** [comment]
@batsirai-sudo Could you help?

**Comment by Batsirai-sudo** [comment]
hey hie ooooo the reason is that the package name for mkgs is already uploaded on Google play store you need to change the package name to lets say
com.yourName.yourName

it act as an id of sort to differentiate evryone projects 
so you need to find different 
do you knw how to change package name or you want me to help you

**Comment by nikolas27** [comment]
Hello, thanks a lot for your reply once again :) 
I should specify that I've tried to change the package name, based on a tutorial I found but it didnt work. Could you tell me how please?

**Comment by Batsirai-sudo** [comment]
oky lemme try to send image explaining to you

**Comment by Batsirai-sudo** [comment]
first change the package name in your manifest line number 13 to the 1 you want

**Comment by nikolas27** [comment]
done

**Comment by Muchareva** [comment]
![20200410_203552](https://user-images.githubusercontent.com/59892662/79014752-d5fbfd80-7b6b-11ea-9fef-8201d3c59c7e.jpg)
![20200410_203616](https://user-images.githubusercontent.com/59892662/79014884-1491b800-7b6c-11ea-92f9-ebb0850ddbb4.jpg)
![20200410_203621](https://user-images.githubusercontent.com/59892662/79015120-7520f500-7b6c-11ea-9d8b-fd9267019983.jpg)
![20200410_203631](https://user-images.githubusercontent.com/59892662/79015228-abf70b00-7b6c-11ea-90f9-a4178f97b552.jpg)

**Comment by Batsirai-sudo** [comment]
oky i dont knw whats happening with my network buh i tried to send some images

**Comment by Batsirai-sudo** [comment]
click the settings icon on like on images and you will see where its written Compat middle packages untick it 


go to your java package and open ot you will see that mgks.os.webview its now separated from there then rename individual when you rename make sure you tick where its written search in comments and strings and search for text occurance 


or else you will be putting a lot of work for yurself

**Comment by Batsirai-sudo** [comment]
the same names you put in manifest should be the same you put for those packages

**Comment by Batsirai-sudo** [comment]
there is a notify of Do refactor click it

**Comment by Batsirai-sudo** [comment]
i think you will be good to go now

**Comment by Batsirai-sudo** [comment]
make sure to delete the build folder and unistall the app before you run it

**Comment by nikolas27** [comment]
sorry for my late response. It worked. Thanks a lot for your contribution :)

**Comment by mgks** [comment]
I believe it's time to close this.

**Comment by fun99** [comment]
Getting below error 

No matching client found for package name "package name"

**Comment by mgks** [comment]
@fun99 when are you getting this error?
