### ISSUE TITLE
Camera support

### ISSUE THREAD

**Issue by nikolas27** [mgks/Android-SmartWebView#106]
Hello, on my WordPress page, i have a custom form where users can upload photos. 
When the "photo upload button" is clicked, the user will have to choose between the camera and the photo folder.

On mgks webview, there is no camera option to select. Only upload from the relevant folder. How can i fix this?

**Comment by mgks** [comment]
can I get more information on your device config?

**Comment by mgks** [comment]
is this issue fixed?
