### ISSUE TITLE
Something went wrong issue

### ISSUE THREAD

**Issue by toofast1** [mgks/Android-SmartWebView#11]
Hello,

I have external links within my app, and when I click those links, I get that notification saying Something went wrong. Also, the page displays this message:

net::ERR_NOT_FOUND or something like that

Any idea what may be causing this?

**Comment by mgks** [comment]
I'm not sure if you are on Emulator or Actual device but I think it's missing Default Browser because in project's variable settings ext. links are supposed to call default browsers to handle the request.
One more thing, does the app also crashes?

**Comment by toofast1** [comment]
Yes, the app gets crashed and that notification message saying Something went wrong still remains visible. I had to reboot my device because of that because it appears on top of everything and I couldn't use the keyboard properly.

**Comment by toofast1** [comment]
Any idea how to solve this?

**Comment by mgks** [comment]
do you have any default browser on the device?

**Comment by toofast1** [comment]
No, but it doesn't happen only to me, it happens on all devices. Already received a lot of 1 star reviews on Play Store because of that.

**Comment by mgks** [comment]
oh man! sorry for your loss!
Can you give me your apps play store URL?

**Comment by toofast1** [comment]
Is there a way I can send it to you in private? I don't want to make it public available here.

**Comment by mgks** [comment]
email me -  getmgks@gmail.com

**Comment by mgks** [comment]
It's the redirects who are causing error in your app.....you need to fix that!

**Comment by khurana3192** [comment]
Hey @mgks , this is happening with me as well, where onReceivedError method gets called multiple times thus leading a crash or making the app and phone unresponsive! Can you help me handle this?
