### ISSUE TITLE
Javascript Vulnerability

### ISSUE THREAD

**Issue by HerbWalsh** [mgks/Android-SmartWebView#118]
just got a notice at Google Play on an apk I uploaded using p_0.1:

Vulnerable Javascript Libraries:
jquery | 3.3.1 | known issue: SNYK-JS-JQUERY-174006 | assets/jquery.js

**Comment by mgks** [comment]
you should remove offline files when uploading to play store, it's just the jquery script in `/assets` directory used to demo offline features.

**Comment by HerbWalsh** [comment]
ok thank you I will have to figure out how to do that
