### ISSUE TITLE
File view and Download ...

### ISSUE THREAD

**Issue by Amit-delhi** [mgks/Android-SmartWebView#125]
first of all very thanks to provide sach a valuable code ..... almost everything is working very fine...

but facing 2 issue ..

1. Not able to save usersname and password instant of code is given..
2. Download files is not working... if i click to download file it create a view only and that was very big or you can say not readable properly . 

please guide how to resolve the both issues

thanks

**Comment by mgks** [comment]
check whether `ASWP_SFORM` is enabled.
please specify device config in which you're facing download issue. I'll look into it by next release.

**Comment by Amit-delhi** [comment]
hi... this was already resolved... thanks
