### ISSUE TITLE
about the play store

### ISSUE THREAD

**Issue by atlantex1** [mgks/Android-SmartWebView#127]
I have a doubt, I understand that the project is open source and the license allows commercial use.

Is this project compatible to upload to the play store?

Are there any known problems or incompatibilities that do not allow the application to reach the play store successfully?

If there are cases of success it would also be good to share them.

I really appreciate your answers.

**Comment by mgks** [comment]
you can easily upload the app to the play store under your signature.

there are few issues reported regarding store publishing, you can look here - #114 #49 #118
