### ISSUE TITLE
How to printing?

### ISSUE THREAD

**Issue by xtrad** [mgks/Android-SmartWebView#128]
I'm using javascript window.print(), it works on chrome mobile, but nothing happen with SmartWebView. Is there any solution for this? Pls help

**Comment by mgks** [comment]
Check the latest **[beta repo](https://github.com/mgks/Android-SmartWebView/tree/beta)** update.

I've added a manual printing method, you can add a custom hyperlink anchor for printing in your webpage like `<a href="print:">Print this webpage</a>`.

**Comment by xtrad** [comment]
Awesome!
You're rock! \m/

**Comment by xtrad** [comment]
Since I'm not familiar with Java/Android Studio. I don't know why this warning come up with this version?

ERROR: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/5.5/userguide/gradle_daemon.html
Process command line: C:\Program Files\Java\jdk1.8.0_221\bin\java.exe -Xmx1536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\user\.gradle\wrapper\dists\gradle-5.5-all\byeise1led9a3w3p149d02kfj\gradle-5.5\lib\gradle-launcher-5.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.5
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

**Comment by mgks** [comment]
Fresh start with the updated source.
Try **Build > Clean Project** then **Build > Rebuild Project**

**Comment by xtrad** [comment]
I found solution for the problem from : https://stackoverflow.com/questions/25009717/android-studio-gradle-project-unable-to-start-the-daemon-process-initializatio
117

The Solution Worked:

1.Open the projects gradle.properties file in android studio
2.Added this line at end of file org.gradle.jvmargs=-Xmx1024m & Save the file
3.Close & reopen the project

**Comment by xtrad** [comment]
Now, I'm facing this:
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
D:\Android\Android-SmartWebView-beta\app\src\nullnull\google-services.json
D:\Android\Android-SmartWebView-beta\app\src\debug\google-services.json
D:\Android\Android-SmartWebView-beta\app\src\nullnullDebug\google-services.json
D:\Android\Android-SmartWebView-beta\app\src\nullnull\debug\google-services.json
D:\Android\Android-SmartWebView-beta\app\src\debug\nullnull\google-services.json
D:\Android\Android-SmartWebView-beta\app\google-services.json

**Comment by xtrad** [comment]
from this forum:
https://stackoverflow.com/questions/42888018/google-services-plugin-cannot-function-without-google-services-json

it says that:
When you add apply plugin: 'com.google.gms.google-services' inside your app-level build.gradle it parses configuration information from the google-services.json file.

You removed google-services.json file, that's why it is not able to parse
So remove the below line too from your app-level build.gradle who triggered parsing to make it work again.

apply plugin: 'com.google.gms.google-services'

**Comment by xtrad** [comment]
so I open the build.gradle and disable this line like this:
// apply plugin: 'com.google.gms.google-services'
and I can Build the project, but I wonder if it will make disabled some function of the app or not?

**Comment by mgks** [comment]
`gms.google-services` plugin and `google-services.json` file are used for firebase notifications here.

If you want to use notifications feature just go to firebase panel and download `google-services.json` file and you're good to go.

**Comment by xtrad** [comment]
Ok. for this time, I don't need the feature at all.
Thanx anyway
