### ISSUE TITLE
exit confirmation

### ISSUE THREAD

**Issue by indrasaputrawardhana** [mgks/Android-SmartWebView#129]
hello mate, 
would you add more feature : confirmation dialog before exit (onbackpressed) , I tried several method but nothing works,I tried [this ](https://android--code.blogspot.com/2017/03/android-webview-back-button-pressed.html) before  ,with no luck

thanks before

**Comment by mgks** [comment]
Hi,
I've just updated the **[beta branch](https://github.com/mgks/Android-SmartWebView/tree/beta)** with exit dialog, check that out.

**Comment by indrasaputrawardhana** [comment]
thanks mate I tried, it work as expected , kudos 👍
