### ISSUE TITLE
Error showing on opening another local file

### ISSUE THREAD

**Issue by sandeepthaliyil** [mgks/Android-SmartWebView#13]
Hello.
Thank you for your SmartWebView Code.

I have an error coming in my webview.

i am using local html file for my project
`"file:///android_asset/www/index.html"`

I am redirecting the user to login.html file if not logged in.
but i am getting an error toast as "`Cannot display PDF (login.html cannot be opened)`"​

Please let me know how to handle navigation.

**Comment by mgks** [comment]
how are you redirecting through JavaScript?

**Comment by sandeepthaliyil** [comment]
Yes, i tried with window.location. 
when that didn't work tried with `a id="logout" href="login.html"`  with auto click on it `$('#logout')[0].click();`
both didn't work.

**Comment by mgks** [comment]
It won't work.
your "login.html" needs to be redirected to projects local directory (android_asset) everytime someone makes request.
So what you can possibly do here is, on every `shouldOverrideUrlLoading` action your project should add directory prefix for requested file and open it in the webview as a new file. Tell me if this works:
```
public boolean url_actions(WebView view, String url){
    ...else{
        aswm_view("file:///android_res/www/"+url,false);
    }
}
```
Replace above code to url_actions() function's else block.

**Comment by sandeepthaliyil** [comment]
No. it didn't work.
this request is going into the last if statement
` if (ASWP_EXTURL && aswm_host(ASWV_URL)!=ASWV_HOST) {}`

**Comment by mgks** [comment]
You know about condition handling right?
Either you set `ASWP_EXTURL` to `false` or remove that whole statement.

**Comment by mgks** [comment]
I guess your issue is resolved by now.
