### ISSUE TITLE
Html select crashes the App

### ISSUE THREAD

**Issue by eksenweb** [mgks/Android-SmartWebView#131]
Android 6.0.1
Html select crashes the App.
I tried many support libraries   
17501-17501/mgks.os.webview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mgks.os.webview, PID: 17501
    Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
    android.content.res.**Resources$NotFoundException**: Resource ID #0x0
....

**Comment by mgks** [comment]
I'm not able to understand your issue.

**Comment by eksenweb** [comment]
Android 6.0.1
Trying to open SELECT tag in Android WebView crashes the application.
 
For example :
<select name="s">
<option value="1">1</option>
<option value="2">2</option>
</select>

i think same error  
https://stackoverflow.com/questions/46208138/why-does-android-os-8-webvew-with-html-select-tag-crash-the-app

**Comment by mgks** [comment]
Seems like a lot of people having this issue.
This might help you - https://issuetracker.google.com/issues/141351441#comment27

**Comment by eksenweb** [comment]
_this might help you - https://issuetracker.google.com/issues/141351441#comment27_
solved thanks.
