### ISSUE TITLE
Camera and Microphone not working

### ISSUE THREAD

**Issue by Nyro-Binag** [mgks/Android-SmartWebView#134]
**Describe the bug**
When I click on the Microphone/Camera button that should ask me to give permission for the app and activate the Microphone/Camera, nothing happens.

**Expected behavior**
I should get a permission request window and then enable that functionality 

**Screenshots**
![Screenshot_20200130-160458_Android_Smart_WebView 1](https://user-images.githubusercontent.com/28536464/73484522-3a3a5e00-4380-11ea-8465-6bb49ab565fa.jpg)

**Device (please complete the following information):**
Samsung Galaxy S8 - 9.0

**Additional context**
I just changed the ASWV_URL on the example project to point to [my website](https://web.superviz.com/login)

**Comment by mgks** [comment]
> When I click on the Microphone/Camera button that should ask me to give permission for the app and activate the Microphone/Camera, nothing happens.

have you added microphone and other permissions required?

**Comment by Nyro-Binag** [comment]
No, I thought that the project handled that automatically. Can you point me in the right direction? Thanks.

**Comment by mgks** [comment]
You need to add microphone permission in the Manifest and MainActivity, camera permissions are already there, so just try doing that first.

**Comment by Nyro-Binag** [comment]
So, as you said, the camera permission is already there, but it doesn't work for me here.

**Comment by mgks** [comment]
I believe your app needs direct stream of information which isn't possible as of now with SWV. You need to integrate WBRTC features in the app to stream any live content.

**Comment by Nyro-Binag** [comment]
Ok, I'll look into that

**Comment by freehussain** [comment]
hello,

i use the same software (bigbluebutton), on chrome it works fine and it's requesting for permission  ,
why in your webview this doesn’t work?

**Comment by mgks** [comment]
@freehussain chrome is not a webview app, it's a chromium engine.
we've very limited resources here to work with.
don't you wonder why is chrome more than 50MB while SWV is just 5MB?
