### ISSUE TITLE
Open Url In WebView

### ISSUE THREAD

**Issue by ReyKar** [mgks/Android-SmartWebView#135]
How can I make my web menu when clicked (faq example) open directly in the webview application, this menu is still 1 domain home.com and home.com/p/faq.html. I mean, I don't open Chrome 3 / default browser So go straight to webview

![IMG_20200202_222236](https://user-images.githubusercontent.com/34483137/73610504-9c0df880-460a-11ea-91e0-73eceb7ad1f8.jpg)

**Comment by mgks** [comment]
You need to edit `intent-filter` in Manifest.
```
android:scheme="https"
android:host="github.com"
android:pathPrefix="/"
```
[update these fields](https://github.com/mgks/Android-SmartWebView/blob/da4c408af0a3f144b993f52660ef091f65f4c214/app/src/main/AndroidManifest.xml#L65) with accordance to your convenience.

**Comment by SyahrulFajar** [comment]
> You need to edit `intent-filter` in Manifest.
> 
> ```
> android:scheme="https"
> android:host="github.com"
> android:pathPrefix="/"
> ```
> 
> [update these fields](https://github.com/mgks/Android-SmartWebView/blob/da4c408af0a3f144b993f52660ef091f65f4c214/app/src/main/AndroidManifest.xml#L66) with accordance to your convenience.

If you change the color of the dialog alert, sir? for example I want to change to / white Thank you in advance

**Comment by SyahrulFajar** [comment]
Background alert dialog

**Comment by ReyKar** [comment]
Hello sir? how do you change the background alert dialog? I tried changing to white there were duplicate colors and not flat like there was padding (messy). pls help

**Comment by mgks** [comment]
you should post different issue threads for different problems.

anyway, you can alter it [here](https://github.com/mgks/Android-SmartWebView/blob/da4c408af0a3f144b993f52660ef091f65f4c214/app/src/main/java/mgks/os/webview/DialogManager.java#L313).

default dialogue theme is Lollipop style but you can use default ones or make custom dialogue designs, just google to find out how to implement it.

**Comment by ReyKar** [comment]
Can I contact you personally via email? please reply, I contact the email on your github profile, thank you in advance @mgks @mgks  Ghazi Khan mgks
