### ISSUE TITLE
Firebase notification when app open help

### ISSUE THREAD

**Issue by djmike3404** [mgks/Android-SmartWebView#137]
I have been trying to get Firebase messaging to work with while the app is open and have had issues. It only wants to receive notifications in the background or when the app is closed.  So I did some research and tinkered a bit and here it want got them working in both the foreground, background and when the app is closed

open the Firebase.java

Look for this

      public void onMessageReceived(RemoteMessage message) {
	     if (message.getData().size() > 0) {
	          sendMyNotification(message.getNotification().getTitle(),
                      message.getNotification().getBody(),
                      message.getNotification().getClickAction(),
                      message.getData().get("uri"));
	     }
     }

change it to this

     public void onMessageReceived(RemoteMessage message) {
              if (message.getNotification() != null) {
		     sendMyNotification(message.getNotification().getTitle(),
			     message.getNotification().getBody(),
			     message.getNotification().getClickAction(),
			     message.getData().get("uri")
		     );

	     }

Notifications will only be shown in the background and when app is closed when using

     message.getData().size() > 0

to get both foreground and background messages use

     message.getNotification() != null

**Comment by atlantex1** [comment]
it would be nice to enable the notification function when the app is open.

**Comment by djmike3404** [comment]
> 
> 
> it would be nice to enable the notification function when the app is open.

@atlantex1 you can get notifications with the app open. It kind of irritated me too that it only worked with the app closed or in the background. To get the working with the app in the foreground open the Firebase.java and look for this

`	public void onMessageReceived(RemoteMessage message) {
		if (message.getData().size() > 0) {
			sendMyNotification(message.getNotification().getTitle(),message.getNotification().getBody(), message.getNotification().getClickAction(), message.getData().get("uri"));
		}
	}`

and change it to this

`		if (message.getNotification() != null) {
			sendMyNotification(message.getNotification().getTitle(),
				message.getNotification().getBody(),
				message.getNotification().getClickAction(),
				message.getData().get("uri")
			);

		}`

It worked for me

**Comment by mgks** [comment]
@djmike3404 thanks for the heads up.
would you mind creating a pull request with your changes?

**Comment by djmike3404** [comment]
@mgks  I would love to but I have never created one as don't wont to post something incorrectly to your project. This issue request was also my first. I'm not real familiar with github. The navigation seems confusing and clunky

**Comment by mgks** [comment]
@djmike3404 it's okay. I've pushed the update with your solution and mentioned you in the commit :)
thanks.
