### ISSUE TITLE
SOLVED - push notification opens specific url in webview

### ISSUE THREAD

**Issue by atlantex1** [mgks/Android-SmartWebView#138]
Would it be possible to include a function where a web address will be sent from fire base push notification and that it will open in webview?

for example you need to send a promotion that is on the website and when it arrives the user accesses it and opens in webview.

If this is already possible, could you please show how it is done?

Many thanks to the team for making this possible!

**Comment by mgks** [comment]
Here you go,
[FCM Documentation](https://github.com/mgks/Android-SmartWebView/blob/master/documentation/fcm.md)

Just in your post request, add/update `data > uri` with your desired URL and webview will open it via notification.

**Comment by atlantex1** [comment]
I had already managed to send push notifications through the firebase console, however I had not been able to open a specific url.

Investigating, I managed to do it with POSTMAN and in a massive way (without creating topic groups), thanks will never be enough for those who made this project possible and for MGKS!

EXAMPLE:

HEADERS:

URL https://fcm.googleapis.com/fcm/send 

content-type: application/json 

authorization: key=____your_server_key_here___ 
(Firebase > Settings > Cloud Messaging > Server key)

BODY (RAW):

{    
"condition": "!('anytopicyoudontwanttouse' in topics)",  // This condition allows mass notifications to be sent to all those who have the APP installed without a specific token.//
   
"notification": {
    "title" : "__Your title__",
    "body" : "__Message of notification__ ",
    "image": "__Url of the image that will show the notification___ ",
    "click_action": "Open_URI"
  },
  
    "data": {
    "uri": "Url  that will open the webview"

    }
}

**Comment by Diaver** [comment]
@atlantex1 
Hey!
Can you please share how did you fix it?
