### ISSUE TITLE
I like it, but it does not open all ...

### ISSUE THREAD

**Issue by dulax** [mgks/Android-SmartWebView#14]
Hello friend, your code (transfer of coordinates by cookie is what I needed), Even so, I have a problem, and is that any url that I enter that has a javascript does not work. Example:
Http://201.150.28.202/smarttrash/index.php?au=58263EE891CCBB4F7428C994EBA47CDB

The idea of this show the location on the map, but unfortunately the JS hangs, what can it be?

Thank you very much.

**Comment by mgks** [comment]
Check your `ASWP_OFFLINE` variable, whether it's true or false.

**Comment by dulax** [comment]
awsp_offline is true

**Comment by mgks** [comment]
Then you should try changing it to false. Or try some little more tweaks,
if still doesn't, feel free to ask.

**Comment by mgks** [comment]
This issue seems to be resolved as no update has been provided by now. I'm closing this.
Feel free to open this issues again if unresolved.
