### ISSUE TITLE
My application closes when a Firebase Push Message arrives.

### ISSUE THREAD

**Issue by EzeOliva** [mgks/Android-SmartWebView#145]
Configure the WebView with my Firebase profile. I have a method that gets the token and saves it in a database. I do a push notification test to that token and upon arrival the message closes the application. My Firebase class is unmodified:

--------------------------------------------
package mgks.os.webview;

import android.app.Notification;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.media.RingtoneManager;
import android.net.Uri;
import android.util.Log;

import androidx.core.app.NotificationCompat;

import com.google.firebase.messaging.RemoteMessage;
import com.google.firebase.messaging.FirebaseMessagingService;

public class Firebase extends FirebaseMessagingService {
public void onNewToken (String s) {
Log.d ("TOKEN_REFRESHED", s); // printing new tokens in logcat
}

public void onMessageReceived (RemoteMessage message) {
if (message.getData (). size ()> 0) {
sendMyNotification (message.getNotification (). getTitle (), message.getNotification (). getBody (), message.getNotification (). getClickAction (), message.getData (). get ("uri"));
}
}

private void sendMyNotification (String title, String message, String click_action, String uri) {
// On click of notification it redirect to this Activity
Intent intent = new Intent (click_action);
intent.putExtra ("uri", uri);
intent.addFlags (Intent.FLAG_ACTIVITY_CLEAR_TOP);
PendingIntent pendingIntent = PendingIntent.getActivity (this, 0, intent, PendingIntent.FLAG_ONE_SHOT);

Uri soundUri = RingtoneManager.getDefaultUri (RingtoneManager.TYPE_NOTIFICATION);
NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder (this, MainActivity.asw_fcm_channel)
.setSmallIcon (R.mipmap.ic_launcher)
.setContentTitle (title)
.setContentText (message)
.setAutoCancel (true)
.setSound (soundUri)
.setContentIntent (pendingIntent);
Notification noti = notificationBuilder.build ();
noti.flags = Notification.DEFAULT_LIGHTS | Notification.FLAG_AUTO_CANCEL;

NotificationManager notificationManager = (NotificationManager) getSystemService (Context.NOTIFICATION_SERVICE);

notificationManager.notify (MainActivity.ASWV_FCM_ID, notificationBuilder.build ());
}

}

**Comment by djmike3404** [comment]
I wrote a different method to receive the firebase messages and display them. It is posted on here somewhere. It works correctly and is in use on the app I wrote everyday

**Comment by mgks** [comment]
@EzeOliva here's the follow up #137 and I guess your repo isn't updated anytime recently, please update.
thanks to @djmike3404 he found the bug first and fixed it.
