### ISSUE TITLE
Change theme color from  dark to light.

### ISSUE THREAD

**Issue by atlantex1** [mgks/Android-SmartWebView#148]
Good morning to all, you can guide me how to change the code so that the context menus appear white with black letters and not a dark gray background.

I would thank you a lot!

![image](https://user-images.githubusercontent.com/58403442/76910047-f392bb80-687a-11ea-8a5a-1b789331c7da.png)

**Comment by mgks** [comment]
It's totally up to the developer, you can add the button that switches between two different style schemes. In webview mode everything can be done on web-end.

**Comment by atlantex1** [comment]
can you help me? please!

**Comment by mgks** [comment]
see, for web end, you need to alter CSS and on apps end, we have our color scheme in `colors.xml` and to make your app able to switch between both themes, here's a trick; just add more colors according to your dark scheme to the same `xml` file and save switches as cookies that will help you on both web and app end.

I guess there's nothing more to it and it's been a while, I'm closing this issue, if you feel like asking more questions, be free to dude.
