### ISSUE TITLE
File google-services.json is missing. 

### ISSUE THREAD

**Issue by nikolas27** [mgks/Android-SmartWebView#154]
Hello after a long time, I hope everyone is safe and well.
When i compile the project, i get this error:

Caused by: org.gradle.api.GradleException: File google-services.json is missing. The Google Services Plugin cannot function without it. 

Any ideas what is wrong here? If it is related to firebase, can you tell me how i switch it off?

**Comment by Batsirai-sudo** [comment]
i came across that problem too but i solved it what i need to know is that do you want to use firebase in your project or

**Comment by nikolas27** [comment]
Hey thanks a lot for your answer. I don't need firebase at all :)

**Comment by Batsirai-sudo** [comment]
remove 

apply ​plugin​: ​'​com.google.gms.google-services​'  


in build.gradle 
 its located at the bottom 
if you remove it will work   


but if you are going to use firebase in future you will need the json file for mobile push notifications and some features 


Enjoy your code.....

**Comment by nikolas27** [comment]
It worked thank you very much :) 
Now it crashes right after the splashscreen, it is going to be along night :)

**Comment by Batsirai-sudo** [comment]
i can walk through with you to make it work its actually ease

**Comment by Batsirai-sudo** [comment]
everything you are facing i also faced it

**Comment by nikolas27** [comment]
Do you have a solution for the restarts?

First i get A message prompting for Gradle update and then a message warning about stale dexed jars that dont match the version... Any recommendations?

**Comment by Batsirai-sudo** [comment]
go to MainActivity remove

 fcm_token on line 264

another fcm_token on line 761 remove the whole else if statement containing it

another fcm_token on line 798 remove it

**Comment by Batsirai-sudo** [comment]
try to use this link for that problem


https://stackoverflow.com/questions/25493310/cant-upload-android-app-to-device-stale-dexed-jars

**Comment by nikolas27** [comment]
Worked like a charm. Thanks a lot for your help. You saved me many many hours of searching

**Comment by atlantex1** [comment]
If You try yo get the Google services.json is easy un future You can send push notificaciones.

Go to firebase site create an acount follow instructions easy.

**Comment by Batsirai-sudo** [comment]
no problem sharing is caring

**Comment by Batsirai-sudo** [comment]
@atlante1 hie atlantex1 i was reading your comments with mkgs dd you find the solution on camera uploads it seems as if i use camera to upload images with SWV its not working but with google chrome its working

**Comment by mgks** [comment]
@Batsirai-sudo can you follow the further camera discussion on the thread you're talking about? We can look in the bug there in detail.

**Comment by Batsirai-sudo** [comment]
sorry am lost where should i follow exactly

**Comment by mgks** [comment]
> sorry am lost where should i follow exactly

I looked through previous issues, last camera thread is closed so you need to open a new issue with details.

**Comment by Sergisoft** [comment]
> Worked like a charm. Thanks a lot for your help. You saved me many many hours of searching

Thanks! I got the exact same sequence of issues.
