### ISSUE TITLE
create_image() on Android Q API 29

### ISSUE THREAD

**Issue by drezr** [mgks/Android-SmartWebView#157]
Hi,

Thanks for your work. I'm a complete beginner at Android developement and tried to build a webview app with aswv.

Something went wrong when i tried to upload a photo taken with the camera.
Seems that the `Environment.getExternalStorageDirectory()` used in the `create_image()` method is deprecated in Android Q. I instead had to use [getExternalFilesDir](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)) to make it work.

FYI [This is where i found the solution](https://stackoverflow.com/a/57116787)

Just so you know.

**Comment by Batsirai-sudo** [comment]
you are a life saver this was cracking my head

**Comment by Batsirai-sudo** [comment]
thank you soo much that was 1 problem i was having with SWV

**Comment by mgks** [comment]
updated in last commit. thanks!
