### ISSUE TITLE
Ability to ignore Firebase/Google service or update README.md on how to create one in Firebase Console

### ISSUE THREAD

**Issue by omerowitz** [mgks/Android-SmartWebView#164]
**Problem**
When first starting this boilerplate, we'll get a build error that we're missing a `google-services.json` which we must acquire from Firebase Console.

It's not a frustration that much, but for novice users it may be misleading.

**My suggested solution(s)**
I would like an easy code-wise ability to fully ignore using Firebase Services (aka. `google-services.json`) for the time being, or to provide a guideline how to create one.

This could be a template for it: https://support.google.com/firebase/answer/7015592?hl=en

**Alternatives**
As described above, two of those solutions should suffice anyone, if not, maybe a way to remove Firebase entirely (someone might not need it at all)

**Comment by atlantex1** [comment]
Maybe the posibility to include a dummy file of services.json to start with out errors

**Comment by mgks** [comment]
I've added my `google-services.json` file in the latest repo, take it as a dummy, atleast the errors won't appear.
