### ISSUE TITLE
QUESTION ABOUT SPLASHSCREEN

### ISSUE THREAD

**Issue by atlantex1** [mgks/Android-SmartWebView#165]
Does the splash screen work while the application is loading in the background or does the application start loading when the splash expires?

If so, would it be possible to modify it so that while the splash is displayed, the application loads the background and thus saves time?

I thank all of you in advance for making this great project possible.

sorry for my bad english.

**Comment by Batsirai-sudo** [comment]
the splash screen is taking over while the application is running in the background

**Comment by mgks** [comment]
Application loads in the background while splash screen is shown. It's been placed there for the same purpose, I hope this helps you understand the app better.

Sorry I've been away from the project for a while now. I hope to be more active now.
