### ISSUE TITLE
facebook authentication suport 

### ISSUE THREAD

**Issue by atlantex1** [mgks/Android-SmartWebView#166]
Nowadays digital identity is very important, for some projects it is difficult to make a user create a profile, that is why it would be very important that this solution be suported in webview.

in the following link there is a discussion on the subject where several programmers found the way to suport this feature, I would like to be more skilled in programming to share a code with the solution, I thank again @mgks  for their generosity in sharing this great project with us.

https://stackoverflow.com/questions/12648099/making-facebook-login-work-with-an-android-webview

**Comment by mgks** [comment]
hey @atlantex1 I absolutely love your enthusiasm with regards to innovation.
I also thought of designing social login plugin for SWV but it's been a while I was busy doing nothing, absolutely unforgiving behavior for someone who wants to keep a project alive. Kind of a public confession that I've been very lazy lately.

But sure now I'll look onto your request and if possible I'd love to make it possible.
Take care man!

**Comment by atlantex1** [comment]
It would be nice if this functionality were implemented

**Comment by mgks** [comment]
the function will be added in future updates, variable has been just introduced for now to keep a reminder of feature.

**Comment by mgks** [comment]
> I see you have this variable ASWV_EXC_LIST but its never used in code anwhere :( Sorry if i am wrong to understand

the function will be added in future updates, variable has been just introduced for now to keep a reminder of feature.

**Comment by convert2xhtml** [comment]
Oo ok great

**Comment by Mainak009** [comment]
> If we make static boolean ASWP_EXTURL = false; I am able to login via facebook and twitter to my app as it opens in same view.
> 
> Though google does not works. and all external links open within Webapp :(
> 
> I saw some where that we can mention domain names that we wish to open within webview and which all we dont want too.
> 
> I tried this // domains allowed to be opened inside webview
> static String ASWV_EXC_LIST = "facebook.com, accounts.google.com, api.twitter.com";
> 
> but that didnt work

For google OAuth login, change **OVERRIDE_USER_AGENT** to _true_ and check by changing the user agent and android version.
