### ISSUE TITLE
google play console security alert

### ISSUE THREAD

**Issue by atlantex1** [mgks/Android-SmartWebView#172]
First of all I would like to thank you for the great work you have done with this application, thanks to it I was able to publish on the play store.

regarding this they gave me an alert in the play console where they warn the following:

"  Security alert

Your app contains one or more libraries with known security issues. For more information, see this article in the Google Help Center.

    Vulnerable JavaScript Libraries:

    Name Version Known issues Identified files
    jquery 3.3.1 SNYK-JS-JQUERY-174006 assets / jquery.js

    It affects version 4 of the APK. "

Could  help me correct this warning to update the project with a correction.

Once again I thank MGKS and all those who contribute to this project

**Comment by mgks** [comment]
I added jquery file for demo purposes to the assets, you can remote it if any offline JS function is not in use. Easy peasy!

**Comment by atlantex1** [comment]
it works thanks!
