### ISSUE TITLE
How to load epub file into webview

### ISSUE THREAD

**Issue by skfaisal93** [mgks/Android-SmartWebView#175]
I could not find anyway to load epub file. Can I load load epub file into webview?

If yes then how?

Please share sample code if possible.

**Comment by mgks** [comment]
I'm not sure if this would be of any help for now. But you might be able to integrate one of these into SWV for starters.
https://github.com/topics/epub-reader?l=java

**Comment by djmike3404** [comment]
Epub.js allows you to render epub docs in a browser. It may solve your issues
