### ISSUE TITLE
firebase push notification

### ISSUE THREAD

**Issue by sumitdas4u** [mgks/Android-SmartWebView#177]
hi i have added the file from firebase but the cloud message is not working

**Comment by mgks** [comment]
please check error logs.

**Comment by dbillwilber** [comment]
Hello, I am a novice in Firebase, I got to send notifications to ALL devices from the Firebase console, but since I send PERSONALIZED notifications and from MySql with AUTOMATED PHP. I don't know if there are tutorials on how to do it. very grateful for your PROJECT.

**Comment by dbillwilber** [comment]
And the other query is: how to store TOKEN in MySql

**Comment by dbillwilber** [comment]
I managed to make everything work, they are geniuses ... thank you very much.
