### ISSUE TITLE
by moving your finger down the update

### ISSUE THREAD

**Issue by susl16c** [mgks/Android-SmartWebView#18]
Can I do while moving my fingers down the site data was updated?

**Comment by mgks** [comment]
nope. it's not there, it depends on developers personal choice whether he/she wants it or not, for any particular directory or not.
That's why didn't add it.

**Comment by susl16c** [comment]
And you can not make it univarsal, so that you can refresh the page with your finger down this same convenient.

**Comment by mgks** [comment]
It's not like that.
In some applications, you need some pages to be not refreshed by any mistake. For example, pages with payment modes or non AJAX forums. With that, a lot of trouble can be created.

I hope this answers your question. I'm closing this issue.

**Comment by mgks** [comment]
Pull to refresh is now added, checkout the update @susl16c
