### ISSUE TITLE
Notification in a group

### ISSUE THREAD

**Issue by bishu** [mgks/Android-SmartWebView#182]
I am sending the notification to the apps using the Firebase Cloud Messaging
Every notification is showing separately.

I use to sent many notification in a day which make problem to the client

How can I show all the notification in a single group.

**Comment by djmike3404** [comment]
I dont think this is possible with firebase messaging. take a peak at the documentation in firebase messaging. I dont think however you can show every notification in a group. I do believe the are char limits to firebase notifications.
