### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by ks1505** [mgks/Android-SmartWebView#185]
class SmartWebView {

    /* -- PERMISSION VARIABLES -- */
    static boolean ASWP_FUPLOAD       = true;         // upload file from webview
    static boolean ASWP_CAMUPLOAD     = true;         // enable upload from camera for photos
    static boolean ASWP_MULFILE       = true;         // upload multiple files in webview
    static boolean ASWP_CP			  = false;		  // enable copy/paste within webview

    static boolean ASWP_PULLFRESH     = true;         // pull refresh current url
}

**Comment by djmike3404** [comment]
As stated in the documentation @mgks wrote, you change the true or false values to either turn on or off the feature. For example... `static boolean ASWP_CAMUPLOAD  = true;` allows you to upload pics as you take them from the camera. Now lets say you did not what this feature. You would change it to `static boolean ASWP_CAMUPLOAD  = false;` "True" means the feature is enabled and "false" means the feature is disabled. You have to physically change these values.

**Comment by shaqtee** [comment]
if only there was a learning video about smart webview on udemy or anywhere else.. it would be great!

**Comment by djmike3404** [comment]
> 
> 
> if only there was a learning video about smart webview on udemy or anywhere else.. it would be great!

There are tons of videos EVERYWHERE on Java. You can watch them on youtube or just about any platform. You first have to understand Java and then SmartWebView will make sense. If you haven't written code before you can start out with something easier like javascript, php or any other object oriented language. Will make it easier to transition into more complicated languages like Java. Being that Kotlin is the official language of Android you could do that too. But the most important thing is write code every chance you get....thats how to stay sharp and open new doors in the coding world.
