### ISSUE TITLE
Image upload gets .3gp extension when video is also available

### ISSUE THREAD

**Issue by amanzan** [mgks/Android-SmartWebView#190]
Testing file upload, I got both image and video available inside intent chooser.

Take a picture, upload it, and it gets the video extension .3gp

**Comment by mgks** [comment]
must a issue of file type selection.

**Comment by amanzan** [comment]
@mgks no, it's because you use the same variable **asw_cam_message** for both photo and video, and the video is the last one to set up. So if photo and video are both present and you select a photo, it will always have the video extension.
The only solution I found is to use 2 different variables for photo and video, and create my own dialog to know what upload option user selects

**Comment by mgks** [comment]
well, I've fixed it as you suggested but it has been mentioned several times in this forum to use file accept type in input, so it becomes intuitive for system to decide whether to activate camcorder or camera. You must be allowing all file types to go through a single input without filtering and I suppose there must be more people doing the same.

Thanks for noticing it anyway.
