### ISSUE TITLE
Remove first splash screen

### ISSUE THREAD

**Issue by jovigor** [mgks/Android-SmartWebView#191]
How can i remove first displayed splash screen?
Since there are two:
- first opens only image front_splash.png (this one i want to remove)
- second opens image front_splash.png, text and links github.com/mkgs - instagram.com/getmkgs
Thanks

**Comment by mgks** [comment]
Only the first one is a splash screen and second one is a load screen, it's inside the main layout xml itself.
You can remove it easily but meanwhile content loads, users will see white screen only, which in my opinion isn't very pretty.

**Comment by Diaver** [comment]
@jovigor 
![image](https://user-images.githubusercontent.com/644716/97658273-4e5fd880-1a42-11eb-9f7d-d3130a54b384.png)

**Comment by jovigor** [comment]
Huge thanks
