### ISSUE TITLE
How to Enable Printing?

### ISSUE THREAD

**Issue by waheedomar** [mgks/Android-SmartWebView#192]
I have configured my Website URL which is Actually an Accounting Software. called ERPNEXT.

I want to print system Generated Invoices As Shown in the screenshot below link.
[https://drive.google.com/file/d/1LwdbX258AYAhquWoDf5y50_gDOFnbO0G/view?usp=sharing](url)

But when i click the print "Circled in Screenshot"
It doesn't work.
As i don't know much about coding.
Please Help me .
Your little Help can make a big solution for me.

Thanks

**Comment by mgks** [comment]
There's a little different method to print the page in SWV, you need to add `href="print:"` to the print button to print current page, you can't print invoice separately. If you want a different/custom solution, you can [email](mailto:getmgks@gmail.com) me.
