### ISSUE TITLE
Is it possible to switch from webview to custom chrome tab without loosing session value

### ISSUE THREAD

**Issue by Sarun1001** [mgks/Android-SmartWebView#195]
When I switch from webview to custom chrome tab I'm loosing  login session of the user, User need to login again inside chrometab, is it possible to retain the session from webview to chrometab

**Comment by mgks** [comment]
there is no option available to share sessions between tabs or either with webview. Nor we can set sessions for tabs, google has not provided any support for that. Users have to login or create sessions separately for each tab.
