### ISSUE TITLE
Not allowing to give camera permission in the weburi which I have added

### ISSUE THREAD

**Issue by XamarinInfo** [mgks/Android-SmartWebView#197]
I have to take pik by using mobile cam.But I am not getting any facility to give the camera permisiion.
I have tried with various urls.

Just for checking the app I tried with - https://webcamtoy.com/

But  I am not allowing to use camera.

What I have to do to get the permissions inside my webview??

**Comment by mgks** [comment]
there are app permissions already mentioned in the app, just check if you have permission variable for camera usage enabled.
