### ISSUE TITLE
FCM Question

### ISSUE THREAD

**Issue by cacacaio** [mgks/Android-SmartWebView#199]
Hey I setup the Firebase and it seems to be working using the FCM_TOKEN using the post method, but I want to know how can I GET the token in my website using something like javascript or other methods to save the token to SQL SERVER

**Comment by mgks** [comment]
cookies are set with the same variable name for such values. just look for updated `FCM_TOKEN` cookies once in a while and save it to your server. easy.

**Comment by cacacaio** [comment]
ohhh ok thanks, and do you know like how long the cookie lasts, and if there is any way to make the token persistent?

**Comment by mgks** [comment]
I was not able to find how long webview keeps cookies as default. For persistence, you need to create a method on server end to keep asking for updated cookies after few days or weeks.

**Comment by cacacaio** [comment]
Ahhh okay then, thanks for the answers ^^
