### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Becks3326** [mgks/Android-SmartWebView#2]
Thank you for the great script! It's perfect for my project. You have done a great job! And thank you for sharing with us!
I'm having trouble with removing the splash screen. I couldn't find anything about it in the documentation.
Could you please help me out? Thanks in advance!

**Comment by mgks** [comment]
If you want to remove the Splash Screen only, you need to remove the SplashScreen activity from AndroidManifest file and add Main activity nod to MainActivity activity.

Remove this:

```
<activity
    android:name="mgks.infeeds.webview.SplashScreen"
    android:launchMode="singleTask"
    android:label="@string/app_name"
    android:screenOrientation="portrait" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
</activity>
```

And add these to MainActivity intent-filter:

```
<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.LAUNCHER" />
```

along with `android:launchMode="singleTask"` and `android:label="@string/app_name"` to the main activity and you're done.

**Comment by nikolas27** [comment]
Sorry but can you be a bit more specific on this:

> And add these to MainActivity intent-filter:

<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.LAUNCHER" />

> along with android:launchMode="singleTask" and android:label="@string/app_name" to the main activity and you're done.

> 
Where exactly?
Thanks a lot

**Comment by mgks** [comment]
You understood this right? what I'm asking you to remove.
> Remove this:
> ...

So, after removing the unwanted code from the manifest, update your MainActivity clause as this:
```
<activity
   android:name=".MainActivity"
   android:launchMode="singleTask"
   android:label="@string/app_name"
   android:screenOrientation="portrait"> <!-- remove or alter as your apps requirement -->
      <intent-filter android:label="@string/app_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"
                    android:host="github.com"
                    android:pathPrefix="/voinsource" /> <!-- if you want only a specific directory from your website to be opened in the app through external links -->
         </intent-filter>
</activity>
```

And that's all you have to do. I hope this helps and let's try to keep this issue closed.

**Comment by nikolas27** [comment]
Sorry for the hassle.
Feel free to delete my message if it is bothering you.
This is a copy of my androidmanifest. It gives an error on install now. Can you have a look please?

   <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/SplashTheme"
		android:hardwareAccelerated="true"
        tools:ignore="AllowBackup">
        <activity
            android:name=".MainActivity"
			android:launchMode="singleTask"
			android:label="@string/app_name"
            android:screenOrientation="portrait" > 
			<intent-filter android:label="@string/app_name">
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="https"
					android:host="github.com"
					android:pathPrefix="/voinsource" /> 
			</intent-filter>
        </activity>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
    </application>

**Comment by nikolas27** [comment]
<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/SplashTheme"
		android:hardwareAccelerated="true"
        tools:ignore="AllowBackup">
        <activity
            android:name=".MainActivity"
			android:launchMode="singleTask"
			android:label="@string/app_name"
            android:screenOrientation="portrait" > 
			<intent-filter android:label="@string/app_name">
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="https"
					android:host="github.com"
					android:pathPrefix="/voinsource" /> 
			</intent-filter>
        </activity>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
    </application>

**Comment by nikolas27** [comment]
`<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/SplashTheme"
		android:hardwareAccelerated="true"
        tools:ignore="AllowBackup">
        <activity
            android:name=".MainActivity"
			android:launchMode="singleTask"
			android:label="@string/app_name"
            android:screenOrientation="portrait" > 
			<intent-filter android:label="@string/app_name">
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="https"
					android:host="github.com"
					android:pathPrefix="/voinsource" /> 
			</intent-filter>
        </activity>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
    </application>`

**Comment by mgks** [comment]
@nikolas27 can you tell more about what error you receive during installation?

**Comment by nikolas27** [comment]
![65698589_625163324637824_8565451478821502976_n](https://user-images.githubusercontent.com/8616765/60382068-a52c5b00-9a66-11e9-8812-950aaa68d02d.jpg)

**Comment by mgks** [comment]
just a screenshot won't help man;
anyway, you can try uninstalling the previous unchanged version (if you already have one installed). It happens to be a problem sometimes and then try installing afresh.

else, you've to google your log error to find what's really going on with your code (you should try practice installing the app via android studio instead of using build APKs everytime). It will save you a lot of time.

**Comment by nikolas27** [comment]
Thanks for your message, i made a fresh install but the problem remains.
Probably some things have changed since 2017, like the " android:name="mgks.infeeds.webview.SplashScreen" which does not exists.

Please write back if you have any ideas regarding the solution.
All the best :)

**Comment by mgks** [comment]
> Probably some things have changed since 2017, like the " 
I'm sorry what version you're using again?

**Comment by nikolas27** [comment]
I am using the latest version of your wonderful app :) and the android studio 3.4.1

**Comment by mgks** [comment]
oh okay, now I understand.
did you removed this from your manifest before build?
```
<activity
            android:name=".SplashScreen"
            android:label="@string/app_name"
            android:screenOrientation="portrait" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by jonnathanlopes** [comment]
I tried it, but the app just doesn't open on the smartphone after the changes

**Comment by atlantex1** [comment]
it would be possible to create a configuration that activates or deactivates the splash screen so less advanced users do not break the code?
