### ISSUE TITLE
Stopped working on changing ads.xml 

### ISSUE THREAD

**Issue by deepakchugh16** [mgks/Android-SmartWebView#200]
Hello,
When I am removing values or updating values in ads.xml. App getting crashed.

<string name="app_id">ca-app-pub-1566476371455791~9278784170</string>
	<string name="test_ad_banner">ca-app-pub-3940256099942544/6300978111</string>
	<string name="ad_banner">ca-app-pub-1566476371455791/3402870453</string>

These are the values which I am not able to update in ads.xml.
Please help.

**Comment by mgks** [comment]
you need to remove ad clause from layout first, isn't your gradle giving errors already? how is your app even building?

**Comment by deepakchugh16** [comment]
I have removed below from activity_main.xml and remove the values from ads.xml. Still it is crashing. I do not want to use admob, is it safe to build apk with your ads.xml values? 
<com.google.android.gms.ads.AdView
		xmlns:ads="http://schemas.android.com/apk/res-auto"
		android:id="@+id/msw_ad_view"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_centerHorizontal="true"
		android:layout_alignParentBottom="true"
		ads:adSize="BANNER"
		ads:adUnitId="@string/ad_banner">
	</com.google.android.gms.ads.AdView>
