### ISSUE TITLE
Message checker

### ISSUE THREAD

**Issue by tfstfs** [mgks/Android-SmartWebView#22]
Great code! Thanks. I have a question. Can you customize your code for me so that the app runs in background and every 5 minutes sends a request to the server (together with webview cookies) to check for new messages? If there are new messages they must appear as notifications with sound y/o vibration and link to the app? If yes, tell me your price for this.

**Comment by mgks** [comment]
You need Firebase for that, it's a lot easier to get notifications than running your app in the background continuously making whole device slow.

Have a nice day friend.
