### ISSUE TITLE
Play Store warning!! Starting May 5th, you must let us know why your app requires broad storage access

### ISSUE THREAD

**Issue by ThemeMetro** [mgks/Android-SmartWebView#224]
I need urgent help to update the help as per google play store new policy. My website allow to  upload  files  from mobile devices.
Starting May 5th, you must let us know why your app requires broad storage access

**Comment by mgks** [comment]
https://www.reddit.com/r/androiddev/comments/mwaqn1/scoped_storage_recap/

this might help you.

**Comment by ThemeMetro** [comment]
Could you please help me, i am not coder, i will pay you.

**Comment by irockstyle** [comment]
sir, it would be a great honor if you add footer navigation (on scroll hide) function in the update but that should not include in the title menu or sidebar ( if separate toggle would be great)

**Comment by mgks** [comment]
> it would be great if you add footer navigation

sure, I'll look into it.
