### ISSUE TITLE
FirebaseInstanceIdService is deprecated

### ISSUE THREAD

**Issue by frogsuite** [mgks/Android-SmartWebView#232]
fcm_token cookie is empty .
 in code we have error

FirebaseInstanceIdService is deprecated

in main activity how to fix this.

**Comment by slimfadi** [comment]
same here

**Comment by mgks** [comment]
Late to the party I guess, while I fix it with next release, you guys can **[follow this solution](https://stackoverflow.com/questions/51123197/firebaseinstanceidservice-is-deprecated)**.
Thanks for reporting.

**Comment by mgks** [comment]
issue is fixed with beta (check the branch).
