### ISSUE TITLE
Failed to validate the certificate chain

### ISSUE THREAD

**Issue by kecoaproject** [mgks/Android-SmartWebView#239]
i get this error can't running url with https in android 6.0 Redmi 4A

`I/cr_X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
I/cr_X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/chromium: [ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -202`

**Comment by mgks** [comment]
There's possibly SSL error coming from your website end.
You have to either bypass SSL Error within the app, or fix issue at the web end for it to work. There are lots of sample codes on stackoverflow for how to do it.

**Comment by kecoaproject** [comment]
> There's possibly SSL error coming from your website end. You have to either bypass SSL Error within the app, or fix issue at the web end for it to work. There are lots of sample codes on stackoverflow for how to do it.

but my website have no problem if running in android 11/ Android 7

**Comment by mgks** [comment]
on what android versions this error is appearing and make sure your SSL is not expired or anything?

**Comment by kecoaproject** [comment]
sorry sir, this problem has solved, after using ssl from cloudflare
thankyou for respond
