### ISSUE TITLE
on click button in webview its displays no internet connection 

### ISSUE THREAD

**Issue by SharfrazAnsari** [mgks/Android-SmartWebView#26]
Hi This is very helpful file i am using in my project i am using my web url for files
home page is opening but when i click to my button its telling please check your internet connection

**Comment by mgks** [comment]
sorry, what button? can you explain a little more?

**Comment by SharfrazAnsari** [comment]
issue was resolved it was from my side only some caching error was there now it is working fine.
 other question when i click on error.html (tap here to retry) it goes to home page i want it to be in same page.

**Comment by mgks** [comment]
good point.
I'll update the repo with the solution asap.

**Comment by shivamfleur** [comment]
It is giving me same problem, when i am clicking on a button which is redirecting me to another link, it is showing no internet connection, and it is happening on just a specific button. Kindly update with the solution.
Thanks in adnvance

**Comment by mgks** [comment]
I've updated the repo., now the problem has been resolved.
You can check and let me know.

I'm closing this issue for now.
