### ISSUE TITLE
404 error on documentation links

### ISSUE THREAD

**Issue by gakenge** [mgks/Android-SmartWebView#272]
Hello, the links to the documentation seem to be offline, could you please point me to the correct links?

Thanks

**Comment by mgks** [comment]
sorry for that, website is currently under few changes so few links are dead. meanwhile you can go through the docs available in repo - https://github.com/mgks/Android-SmartWebView/tree/master/documentation

I'll update this issue with live links once it is fixed.

**Comment by gakenge** [comment]
Ok, thanks
