### ISSUE TITLE
OneSignal - Multi-platform Push Notification Service

### ISSUE THREAD

**Issue by Nemra1** [mgks/Android-SmartWebView#30]
im glad to find Android-SmartWebView project in my way and i hope to add OneSignal  Push Notification addons in SmartWebView
https://onesignal.com/

**Comment by mgks** [comment]
This one line I'm not able to grasp completely "OneSignal makes money by selling data to advertisers and research companies."
What kind of data exactly?

**Comment by Nemra1** [comment]
its just we need send Push Notification  , u can used firebase service and make manual for users

**Comment by mgks** [comment]
okay. so you want me to implement a notification method to the main project itself?

**Comment by Nemra1** [comment]
yes sure.. if u can

**Comment by mgks** [comment]
I'll think about it.
