### ISSUE TITLE
when I build the app it sho me following errors.

### ISSUE THREAD

**Issue by cyleunggg** [mgks/Android-SmartWebView#31]
i amusing android studio 3.1.2 and force to change androidTestCompile to androidTestimplementation

Could not find method androidTestimplementation() for arguments [com.android.support.test.espresso:espresso-core:2.2.2, build_dgz0z00s1zugz2h20notdwp5n$_run_closure2$_closure7@3ece0eea] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
Open File

**Comment by mgks** [comment]
It maybe a syntax error, can you paste your dependency clause here? I want to see how you implement it.
And yeah, `compile` no more viable in near future, you should already start using `implementation` method.

Also, check if your Gradle is updated.

**Comment by mgks** [comment]
Is it working now?

**Comment by mgks** [comment]
Updated Dependencies have deprecated `Compile`, instead use `Implementation` in your gradle module syntax.

That's it.
