### ISSUE TITLE
Any plans for 8.0 API 26 Support?

### ISSUE THREAD

**Issue by vankerre** [mgks/Android-SmartWebView#32]
Notifications and permission changed, also the upload doesn't work when taking picture directly from the camera to a <input type='file'>.

I've been using for a while it now and works wonders till API 25.

My question is should I update the code? Or do you have some WIP ?

Thanks for the amazing app.

**Comment by vankerre** [comment]
I'll see what I can do, I'm a PHP developer myself just now getting to fiddle with Java.

Again, thanks for your app.

**Comment by mgks** [comment]
Added a Fix. Now it's working fine till android P devices.
Re-open the issue if you found any problem.
