### ISSUE TITLE
Gps location doesnt work 

### ISSUE THREAD

**Issue by rozaidi78** [mgks/Android-SmartWebView#34]
hi, thanks for this awesome code, i try it with google map javascript and geolocoding api, but gps location doesnt seem to work. have anyone have this problem?

example
https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

**Comment by mgks** [comment]
does it loads the map? or shows wrong location?
also, why are you using geolocation when you can retrieve accurate GPS locations and pin it on google maps?

**Comment by rozaidi78** [comment]
map does load. but it does not show location. im using geolocation because
im using google map api.

**Comment by timhj** [comment]
Yeah - I had to sort this out for my project so have put the fixes into a fork and sent a pull request. You can view the diff here (https://github.com/mgks/Android-SmartWebView/pull/36/files) if you want to copy it across yourself.

**Comment by rozaidi78** [comment]
Thank for this code.
