### ISSUE TITLE
ASWP_CAMUPLOAD

### ISSUE THREAD

**Issue by cerjo77** [mgks/Android-SmartWebView#37]
Everything is working fine. 
Thank you for this great project.
I just have an issue managing the CAM_UPLOAD.

I can't find how to set the camera as default to upload an image. When i hit the button to upload an image, it opens the file manager.

I had set ASWP_FUPLOAD and ASWP_CAMUPLOAD as true, and in my html file I use this tag to select an image "<input type='file' style='display:none;' accept='image/*' capture name='userImage' required>"

How can I set the camera as the default, or olny option for upload images?

Thank you in advance.

**Comment by mgks** [comment]
Hey. Thanks man. I'm glad you liked it.
I've just updated the repo and added a new variable, ASWP_ONLYCAM which you can use accordingly. For Camera only files.
Update your current repo with newly added tweak and you're good to go.
You're welcome.
