### ISSUE TITLE
App says no internet or slow internet once logged in

### ISSUE THREAD

**Issue by SequoiaChris** [mgks/Android-SmartWebView#41]
![screenshot 20](https://user-images.githubusercontent.com/42925275/44968685-127e6680-aefe-11e8-9d9c-dc0954574fe3.png)

Happens on the emulator and on my galaxy note 8. On wifi and cell internet. I have plenty of mb/s, 200+. I don't know if it is the app, but my site works fine any other way when I access. Any help would be appreciated.

Chris

**Comment by mgks** [comment]
Thank you for letting me know this. I'll look into the issue ASAP.

**Comment by SequoiaChris** [comment]
Thank you for the quick response. I can send over logs or other information when I am back at my home office this evening if that will help at all. When I first access my site, everything flows through correctly. The first page is a login page. Once I have logged in, then I can see the first splash page no problem. I only encounter the error when I subsequently hit the continue page from that splash page and then I am introduced to the "feed" on my site. I think it has something to do with that, but I am not sure what to do because it works just fine when accessing from any where else.

I appreciate your help with this immensely.

**Comment by mgks** [comment]
Hi.
I just updated the repo., see if that works for you.
If I'm not wrong, the actual problem you were seeing was the second error handler `onReceivedError` I added for extra security. But it was causing more problem than helping.

Anyway, I ripped it now, update your project and let me know if it's working now.
