### ISSUE TITLE
Take screenshot from HTML Web Page

### ISSUE THREAD

**Issue by Federico779** [mgks/Android-SmartWebView#42]
Hi, it is possible to take a screenshot in the SmartWebView?
I use this javascript code on android and it works with any browser.
`<script>
                    $(document).ready(function () {
                        $('#save_image_locally').click(function () {
                            document.getElementById("save_image_locally").style.visibility="hidden";
                            html2canvas($('#mydiv'),
                                    {
                                        onrendered: function (canvas) {
                                            var a = $("<a>").attr("href", canvas.toDataURL('image/png'))
                                                    .attr("download", "xxx.png")
                                                    .appendTo("body");
                                            a[0].click();
                                            a.remove();
                                           document.getElementById("save_image_locally").style.visibility="visible";
                                        }
                                    });
                        });
                    });
</script>`
How can I implement it in the SmartWebView?

**Comment by mgks** [comment]
I've not idea what you actually want to achieve at the moment but I'll do look into it.

**Comment by Federico779** [comment]
Thanks for the answer and sorry for my english, I tried to start this https://jsfiddle.net/AbdiasSoftware/7PRNN/ page through the webview but when I click on "Download as Image" the application crashes. Can you help me?
