### ISSUE TITLE
Litle title mistake

### ISSUE THREAD

**Issue by SylvainPoree** [mgks/Android-SmartWebView#43]
In MainActivity.java I suspect : 
 case 2:
builder.setTicker(getString(R.string.app_name));
 builder.setContentTitle(getString(R.string.app_name));
should be 
 case 2:
builder.setTicker(getString(R.string.app_name));
 builder.setContentTitle(getString(R.string.loc_perm));

**Comment by mgks** [comment]
Thanks man!
I've just updated the repo, do let me know if you found anything else.
