### ISSUE TITLE
File chooser display a Camera even if ASWP_CAMUPLOAD is false

### ISSUE THREAD

**Issue by SylvainPoree** [mgks/Android-SmartWebView#44]
Code change suggestion : 
REPLACE
Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
if (ASWP_CAMUPLOAD) {
BY
Intent takePictureIntent = null;
if (ASWP_CAMUPLOAD) {
	takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);

OTHERWISE THE TEST 
if (takePictureIntent != null)
IS A NON SENSE.

**Comment by mgks** [comment]
Repo Updated.
Thanks!
