### ISSUE TITLE
Cant' download file with Content-Disposition: attachment; filename="file.pdf"

### ISSUE THREAD

**Issue by claudiorivetti** [mgks/Android-SmartWebView#48]
Downloading a file on server now works fine. However when trying to download a file served by a perl script via Content-Disposition: attachment; filename="xyz.txt", the file is not downloaded.

cl.

**Comment by claudiorivetti** [comment]
After several experiments I realized that download via Content-Disposition: attachment;  doesn't work when it is the results of a form submit with method=post. Changing method=get it works. Is there any simple solution that makes it work also with post?

cl.

**Comment by mgks** [comment]
Get that you got it working.
I'm not very sure how to get it working with POST method as I haven't testing it myself.
Also, I'm closing this issue for now, it's kind of resolved.
