### ISSUE TITLE
google Play Submission

### ISSUE THREAD

**Issue by smohannagaraj** [mgks/Android-SmartWebView#49]
Hi!
I am a new guy and learning about developing apps.
I came to know google is too hard to developers since it suspends app without any information.
Can you please guide me about it?

Thank U!

I asked you because I decided to use your template.

**Comment by mgks** [comment]
I'm really not able to get your actual point.
In what context you actually need my help?

**Comment by smohannagaraj** [comment]
Guidelines for submitting app and do's and dont's in creating an app.

**Comment by mgks** [comment]
Okay, these are few points you can look into:
- Remember to update the package name before uploading (don't use the one I'm using in the project).
- Keep your signed key safe as it will help you generate future variants of the same app.
- Should remove any extra permission(s) from the Manifest that your project doesn't requires.
- And just upload it.

I guess that's enough to get started and you'll understand things along once you get into the process yourself. All the best.
