### ISSUE TITLE
accept="image/*" capture=environment

### ISSUE THREAD

**Issue by smohannagaraj** [mgks/Android-SmartWebView#51]
This app supports
`<input type="file" name="image" accept="image/*" capture="user">`  ?
Because the app previously i was using is not working.

Please clarify me.  Thankyou

**Comment by mgks** [comment]
I suggest you to read [README.md](https://github.com/mgks/Android-SmartWebView/blob/master/README.md)

I've already mentioned a variable `ASWV_F_TYPE   = "*/*";` where you can mention what file type to be uploaded via app.

**Comment by smohannagaraj** [comment]
> I've already mentioned a variable ASWV_F_TYPE = "*/*"; where you can mention what file type to be uploaded via app.

Yes.  I want to do it for a custom input element inside html page.  Also only for some elements, not for all elements.

When I open my site, in chrome it directly opens the camera.  But though app it shows open doc/img.

Can I explain more?

**Comment by smohannagaraj** [comment]
Plz refer these links. 
https://mobilehtml5.org/ts/?id=23
https://w3c.github.io/html-media-capture/

**Comment by mgks** [comment]
Have you tested the app or not yet?

**Comment by smohannagaraj** [comment]
No.  I still under developing.

**Comment by mgks** [comment]
I suggest you should test it first with making required changes.
