### ISSUE TITLE
Camera will only allow photos, you cannot record video.

### ISSUE THREAD

**Issue by DarraghB** [mgks/Android-SmartWebView#52]
In the file chooser, it allows you to take photos. The camcorder button is greyed out even when I try select that. But you can select previously recorded videos.

**Comment by mgks** [comment]
In this project camera is intended to take just photos as of now.

**Comment by DarraghB** [comment]
Could you add the code to allow videos also?

**Comment by mgks** [comment]
sorry not at the moment but can look into it sometime, in near future.

**Comment by DarraghB** [comment]
Hi Mgks, ive added video upload support. Do you want me to add this to repo?

**Comment by mgks** [comment]
sure, that will be great.
