### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by WaleedJubeh** [mgks/Android-SmartWebView#53]
Dear sir...
Great Job thanks for making the project open source...
I read the documentation to see how to enable multiple files ...
I made the variable true ...
Then i tested it ...
The problem is i select multiple files but in the page appear that i   select one file...???

**Comment by smohannagaraj** [comment]
Check if your page allows multiple file uploading.

**Comment by WaleedJubeh** [comment]
i checked and its true value 
but still not work

**Comment by mgks** [comment]
have you checked whether your HTML form input allows multiple files or not?

**Comment by mgks** [comment]
As of now now, I've tested it several times on different devices and websites, it's working all good now.
Update your repo with the latest updates.
