### ISSUE TITLE
Image doesn't show after capture from camera in marshmallow but works in oreo

### ISSUE THREAD

**Issue by Dani8888** [mgks/Android-SmartWebView#54]
when i take a picture from camera, and the image will show in this img using this jquery, it works in oreo but is does not work in marshmallow.
Look at in this jsfiddle http://jsfiddle.net/t6UP5/978/

**Comment by mgks** [comment]
That issue does exists, it's an internal thing which I have not looked into personally but I guess it's just webview's own way of handling actions in different versions.

**Comment by Dani8888** [comment]
it is work in oreo, i think this is not from web handling but this is about permission to get path of pictures in ActivityResult or MANIFEST PERMISSIONS for marshmallow.

**Comment by Dani8888** [comment]
i'm really need this, is there any solution?

**Comment by mgks** [comment]
I can't keep this issue opened now, I hope you've resolved it by now.
If not, please update us also.

**Comment by Dani8888** [comment]
The issue hasn't been solved yet

**Comment by Alviker** [comment]
Hi there! I have the same problem :( Any help, please?

Thanks for this project!
