### ISSUE TITLE
camera not working and file upload not working in some phones

### ISSUE THREAD

**Issue by HerbWalsh** [mgks/Android-SmartWebView#58]
I have not gotten the cam to work at all and the file upload works on some cameras and not on others..just a guess maybe you need to add Camera2 permissions..are you thinking of adding this?

**Comment by mgks** [comment]
I'm not sure what device you're using.
As for camera2api, I haven't tested it yet and if you're thinking about giving it a try, sure do.
Start with your manifest and let me know if it works.
`<uses-feature android:name="android.hardware.camera2.full"/>`

**Comment by HerbWalsh** [comment]
I switched to your new gradle code and camera and file upload is working well now..one issue but I think it is a server side problem not a SmartWebView issue

			//noinspection GradleCompatible
			implementation 'com.android.support:appcompat-v7:28.0.0'
			testImplementation 'junit:junit:4.12'
			implementation 'com.google.android.gms:play-services-auth:16.0.1'
			implementation 'com.google.android.gms:play-services-location:16.0.0'

**Comment by mgks** [comment]
I'm glad it worked. :relaxed:
