### ISSUE TITLE
Cannot Get User's Location

### ISSUE THREAD

**Issue by DonaldKBrown** [mgks/Android-SmartWebView#59]
I've enabled location, and it asks for permission on first run. However, when trying to actually get the location on a web-page, it doesn't work. I'm using the `navigator.geolocation.watchPosition` method on my web-page to get the location.

**Comment by mgks** [comment]
GPS location is saved in a cookie separately, not universally set for the webview to be retrieved by any web page.
Instead you can fetch the cookies `lat` and `long` set for `ASWV_URL` for precise latitude and longitude, that will be much more accurate.
