### ISSUE TITLE
Domain hosts

### ISSUE THREAD

**Issue by ajdin1997** [mgks/Android-SmartWebView#62]
How to allow only specific domain hosts to be opened in the application? otherwise do nothing/do not open them?

**Comment by mgks** [comment]
Config file has the variable `ASWP_EXTURL` which is `true` by default and will be enough to handle external domains other your default domain set in `ASWV_URL`.

But if you need multiple domains to be handled by the app, you can alter the method `url_actions` accordingly from MainActivity.

**Comment by ajdin1997** [comment]
In my website i have buttons which redirects to different domains/hosts on click, i do not want to open them in app browser or external browser. i need to allow only specifiy hosts to be opened in only app. I am sorry for my english trying to explain as much i can. Here is example i have found in other apps, maybe this explains you better than i: 

@Override
 public boolean shouldOverrideUrlLoading(WebView view, String url) {
  String urlHost = Uri.parse(url).getHost();
  switch (urlHost) {
   case "www.filmoviplex.com":
    return false;
   case "openload.co":
    return false;
   case "oload.tv":
    return false;
   default:
    return true;
  }
 }

**Comment by ajdin1997** [comment]
I fixed, thank you for the support, and i found another problem, when i open embedable video in app it does not fit the screen and i can move it with mouse, is that a bug or something?

**Comment by mgks** [comment]
I haven't tested videos in the webview yet.
You can add the repo to your watch, fork, or just star it so you'll know once I get upto that update.

Here's a small request also,
If you feel like using a smarter version of this project you can get SWV Pro, that will support me also - https://voinsource.github.io/SmartWebView-Pro/

It has many more features like notifications, drawers, admob etc. 
*"sorry, kinda advertising myself but I've to."*
