### ISSUE TITLE
Full Screen Application & Package Change

### ISSUE THREAD

**Issue by ajdin1997** [mgks/Android-SmartWebView#64]
I will open this as new post. Is it possible to make application goes full screen. I have tried to add     android:theme="@android:style/Theme.NoTitleBar.Fullscreen" but this gives errors because app is not compatible with this. and if its possible to make it full screen app, can you help me?

#Package Change

I tried to rename mgks > os >webview but it gives some errors i followed instructions on google how to change package name btw.

**Comment by mgks** [comment]
this application is already using a full screen theme and don't rename the folders.
Here: `Build > Edit Flavors > Application Id` just rename that.
