### ISSUE TITLE
error when opening messenger on facebook page.

### ISSUE THREAD

**Issue by miinoru** [mgks/Android-SmartWebView#67]
**Describe the bug**
error when opening messenger on facebook page.

**Expected behavior**
it opens many error pages and does not stop.
Any way to show no error message? or only one?
sorry me english :(

**Device (please complete the following information):**
 - Device name/variant: Samsung S6
 - Build :
`	static boolean ASWP_JSCRIPT     = true;
	static boolean ASWP_FUPLOAD     = true;
	static boolean ASWP_CAMUPLOAD   = true;
	static boolean ASWP_ONLYCAM  = false;
 	static boolean ASWP_MULFILE     = false;
	static boolean ASWP_LOCATION    = false;
	static boolean ASWP_RATINGS     = true;
	static boolean ASWP_PBAR        = true;  
	static boolean ASWP_ZOOM        = false;
	static boolean ASWP_SFORM       = true; 
	static boolean ASWP_OFFLINE     = false; 
	static boolean ASWP_EXTURL      = false;  
`
 - Android Version : 7

**Additional context**
![screenshot_20190102-122523](https://user-images.githubusercontent.com/17936950/50606408-46a56c00-0e8b-11e9-8795-f8170386d598.png)
![screenshot_20190102-122533](https://user-images.githubusercontent.com/17936950/50606407-46a56c00-0e8b-11e9-8ce5-ea7cd1404c26.png)

**Comment by mgks** [comment]
Facebook page throws error which triggers our local error page.
There are numerous issues, like the `raw` folder that stopped working after a while, so I've changed the error folder to assets.

Try updating your repo and check what error facebook page throws in the log, so we can continue further.
