### ISSUE TITLE
Enable javascript

### ISSUE THREAD

**Issue by SkylerGatibaru** [mgks/Android-SmartWebView#7]
Hi @mgks im trying to run the app but im finding a javascript block.
Please help me on this.
![khan](https://cloud.githubusercontent.com/assets/25096223/24598380/c3404878-1853-11e7-8243-e95901a97af9.png)

**Comment by SkylerGatibaru** [comment]
found it... on the webview setting, i added 

`webSettings.setJavaScriptEnabled(true);`

**Comment by mgks** [comment]
which means.......you've solved it! Right?
I'm closing this issue, if not yet resolved, reopen this anytime.
