### ISSUE TITLE
Does SWV support Navigator.getUserMedia()?

### ISSUE THREAD

**Issue by darthdaniel16** [mgks/Android-SmartWebView#70]
Hi,

Really appreciate the work you have put in. Just started getting into using webview and this project has been a major help. I have had some trouble accessing my camera though. I am testing a streaming site and on a desktop/laptop browser, using the code

    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>getUserMedia  Test</title>
        <link rel="stylesheet" href="style.css">
     </head>
     <body>
       <div id="video-container">
            <video autoplay></video>

	   <script>
	     const constraints = {
	            video: true,
	             audio: true
	      };

	    const video = document.querySelector('video');

	    navigator.mediaDevices.getUserMedia(constraints).
	    then((stream) => {video.srcObject = stream});
	   </script>
         </div>
       </body>
    </html>

allows me to access and view video feed from my laptop/web cam. When i test the site with SWV, it displays the "<video>" object but with no feed from camera. I wanted to inquire whether getUserMedia was supported and if not could you advise on how I can accomplish this?

Thanks

**Comment by mgks** [comment]
Sorry for the late response.

Actually this won't work as your web service isn't directly using the android functions (none of them do).
There are 3rd party services used to make that connection possible and live streaming from android camera through webview javascript is really not possible at the moment.

I hope this answers your question :)
