### ISSUE TITLE
How to Stop YouTube videos from playing in the background of the app

### ISSUE THREAD

**Issue by hotpiez** [mgks/Android-SmartWebView#73]
Is there any way to stop YouTube videos from playing in the backgound of my app.  Videos are embeded in user posts but as far as I can see only play when started in the post and when you go to a different page they close but google has removed my app saying they are playing in the background of the app..any thoughts would be appreciated

**Comment by mgks** [comment]
Try adding:
```
	@Override
	public void onPause() {
		super.onPause();
		asw_view.onPause();
	}
```
and also add `asw_view.onResume();` in `onResume()` clause.
