### ISSUE TITLE
SwipeRefreshLayout & Progressbar request

### ISSUE THREAD

**Issue by Zulhari** [mgks/Android-SmartWebView#75]
Help..... how to add SwipeRefreshLayout & Progressbar ???
I try to add... but still error... 
Thankyou...

**Comment by mgks** [comment]
Hi,
Sorry for this late response. I'll soon work on swipe feature, though SWV already has a progress bar that you can customize accordingly.

Start with setting:
```
ASWP_PBAR = true;
```

**Comment by Zulhari** [comment]
Thankyou mr... your program is powerfull... i like it...

**Comment by mgks** [comment]
checkout the update, I hope you'll like that :)

**Comment by Zulhari** [comment]
Thankyou mr

Pada tanggal Sen, 25 Feb 2019 21:39, Ghazi Khan <notifications@github.com>
menulis:
