### ISSUE TITLE
multiple file upload does not work

### ISSUE THREAD

**Issue by wreck145** [mgks/Android-SmartWebView#76]
**Describe the bug**
My HTML:
```
<form method="post" enctype="multipart/form-data" action="">
<input type="file" name="my_file_upload[]" id="my_file_upload" multiple="multiple">
```

`ASWP_MULFILE = true;`

I can *select* multiple files through my phone's file manager, but only 1 file makes it onto the `<input> `html. Submitting it also doesn't upload the file.

The website works perfectly on desktop Chrome, and external browser Android Chrome App.

**Expected behavior**
Multiple files be uploaded

**Device (please complete the following information):**
 - Device name/variant: Samsung S9+
 - Android Version API 28

**Comment by mgks** [comment]
Multiple file upload is fixed and bug free now. 👍
