### ISSUE TITLE
Long tap to paste is not working

### ISSUE THREAD

**Issue by djaafrinacer** [mgks/Android-SmartWebView#78]
Hello
When I long tap inside an input, it doesn't show the options like copy and paste, can you please help me out?
Thanks again for this great work!!

**Comment by mgks** [comment]
Hi,
Actually this feature was disabled intentionally by v3.0 release. You can re-enable this by commenting out the following event listener from MainActivity:
```
asw_view.setOnLongClickListener(...);
```
