### ISSUE TITLE
Google Navigation not work

### ISSUE THREAD

**Issue by MuhammadJavedRamzan** [mgks/Android-SmartWebView#79]
**Describe the bug**
Sir Really appreciate your work. you did an amazing job. I face an issue my url contain some google navogation so its show google map and everything fine but when I click on NAVIGATE it shows internet connection error.
you can find images below. Please waiting for your response

**Screenshots**
App:
https://drive.google.com/file/d/1BJ7ZNueI2d7_YX9HMje2cLiDeGhFlupS/view?usp=sharing
Logcat:
https://drive.google.com/file/d/1j4LZd5wpBwp4opqcFFz-jvLkndgGKhtj/view?usp=sharing

**Device (please complete the following information):**
Xoimi mi max API 23
and some other devices as well

**Comment by mgks** [comment]
are you trying to navigate within the webview or trying to open an external map?

**Comment by MuhammadJavedRamzan** [comment]
sir i'm trying to open in external map

**Comment by mgks** [comment]
that means SWV isn't able to understand your specific request. better add a new condition in `url_actions` as:
```java
if(url.startsWith("https://maps.google.com")){ //or whatever the intended url is
  //this will launch default tool available for particular task/URL
   Intent intent = new Intent(android.content.Intent.ACTION_VIEW, Uri.parse(url));
   startActivity(intent);
}
```
you can create your own custom intent. hope this helps.

**Comment by MuhammadJavedRamzan** [comment]
Thank you, sir, for your response
