### ISSUE TITLE
Great Job!  I am just having 1 issue

### ISSUE THREAD

**Issue by jhuckstead** [mgks/Android-SmartWebView#8]
Hello,

I love what you have done here.  I am just having one issue...

When I put my PAGE URL in, the it freezes my page on load, no links, or js works... But when I put my homepage in, I can browse to the same page url and everything works perfect... I tried substituting my domain in for the domain variable and it did nothing.  I though maybe it was the ".html" on the end of the URL, so I did a rerwite without it, and still no change.  I noticed a lot of functions that use ASWV_URL and ASWV_HOST... I am busy trying to debug it, but if you have any direction, I would appreciate it.  Ty

**Comment by mgks** [comment]
First, I'm really sorry for replying you so late.
I hope you've resolved the issue by now, if not, don't worry I'll look into it and try to update here the same ASAP.

**Comment by jhuckstead** [comment]
Hey,

Its ok... you don't need to apologize.  Your template was an amazing help to my app.  Thank you so much.
I never found a fix in the code, but I did find a work-around.  I created a page without .html in the url and I did a meta-redirect to the page I needed to go to.

If you want to give me your email, I will send you the url that was giving the issue...

**Comment by mgks** [comment]
sure... please email me that at getmgks@gmail.com
