### ISSUE TITLE
push notifications not showing

### ISSUE THREAD

**Issue by djaafrinacer** [mgks/Android-SmartWebView#84]
Hello
When I browse a webste that has push notifications, no authorization is asked for and therefore no push notifications are receivedn is this feature supported and how to activate it?
Thanks alot

**Comment by mgks** [comment]
are you talking about browser based notifications or mobile push notifications?

**Comment by mgks** [comment]
if it's about browser based, basic webview won't work that way until it's designed like that. Like in our case it's not needed nor will be conventionally nice.
