### ISSUE TITLE
Getting url from external source and loading

### ISSUE THREAD

**Issue by surya1999** [mgks/Android-SmartWebView#87]
I created a WebView that loads the URL google.com when the app is launched.

I also added the URL schema to detect the supported URLs. 

But when the user clicks on the link such as google.com / blog from external source like WhatsApp the app prompts with the open with action menu, but on selection it  load the URL default URL google.com instead of google.com/blog.

Can you help me with the code

**Comment by surya1999** [comment]
https://pastebin.com/LfHPp8KQ link to my code

**Comment by mgks** [comment]
I'm sorry, I believe you're not asking a question with regards to current project.
