### ISSUE TITLE
depending select

### ISSUE THREAD

**Issue by Macof08** [mgks/Android-SmartWebView#88]
In mi page i have depending selects using php, jquery & mysql is from states, when i open mi page with your webview dont cach the selects, its enable javascript.

static boolean ASWP_JSCRIPT    = true;

**Comment by smohannagaraj** [comment]
May be any problem caused by incorrect http & https url.
I am sure this is not the problem in webview.  Can you give the same code or the url?

**Comment by Macof08** [comment]
the ajax code is:

$(document).ready(function() {
	  $.ajax({
type: "POST",
url: "procesar-estados.php",
data: { estados : "Mexico" } 
}).done(function(data){
$("#jmr_contacto_estado").html(data);
});

$("#jmr_contacto_estado").change(function(){
var estado = $("#jmr_contacto_estado option:selected").val();
$.ajax({
type: "POST",
url: "procesar-estados.php",
data: { municipios : estado } 
}).done(function(data){
$("#jmr_contacto_municipio").html(data);
});
});
			});

The url is: https://tufiestapp.com

**Comment by mgks** [comment]
can you try putting complete url in your ajax request?
try - `https://tufiestapp.com/procesar-estados.php` instead of just `procesar-estados.php`

**Comment by Macof08** [comment]
@mgks  it works, much thanks!! i will test it, and if i like it, i would buy the complete versión.
