### ISSUE TITLE
goodwork. one issue /question

### ISSUE THREAD

**Issue by coreykunak** [mgks/Android-SmartWebView#9]
Hello
quick question regarding geolocation

is there a way to use the geolocation without the use of cookies?

example if i put this site in https://www.w3schools.com/html/html5_geolocation.asp
and hit try it. the location does not load.

**Comment by mgks** [comment]
Hey,
Glad you asked. I actually tried using this also to make the system bulletproof but geolocation is something which is browser based and you've to ask for permission for the location I guess, as in browsers. Which makes the app look like any other browser app, which I tried to not look like.

Else, you can easily integrate it in with help from here - http://stackoverflow.com/questions/5329662/android-webview-geolocation

And regarding cookies, I found it the best possible option for now to communicate between app and webpages and it works on both end, any of them can read or write the message. I also tried GET method in previous updates to replace cookies but it makes the app flawed and sometimes redirects with requests.

And tell me if you're facing issues with getting proper GPS locations on update.

**Comment by coreykunak** [comment]
i know i need to add this 
            @Override
            public void onGeolocationPermissionsShowPrompt(final String origin,
                                                           final GeolocationPermissions.Callback callback) {

                callback.invoke(origin, true, false);

i am not sure where i would implement it in your code.

my website has a get location button and when i press it it say i have no permission.

**Comment by mgks** [comment]
Are you sure you already enabled Location variable and permission in manifest?

**Comment by mgks** [comment]
Please close the issue if it's resolved or atleast inform me it's resolved.
Better if you can explain how you solved your problem, or i'll close this issue myself.
