### ISSUE TITLE
Removing the splash screen

### ISSUE THREAD

**Issue by nikolas27** [mgks/Android-SmartWebView#91]
Hello, what is the best way to remove the splash screen?
Thanks a lot in advance

**Comment by smohannagaraj** [comment]
I don't know this will work or not.  But try this:
[Go to this line](https://github.com/mgks/Android-SmartWebView/blob/f7c64219dcb2d6bcfb6a2b19a6236d0750666995/app/src/main/java/mgks/os/webview/SplashScreen.java#L15) and set timeout 0.  If 0 not working then set a small number like 1.

**Comment by smohannagaraj** [comment]
Or just simply comment out the lines 16-33.

**Comment by nikolas27** [comment]
Appreciate your answer but None of the above worked for me. any other tips?
Thanks a lot in advance

**Comment by mgks** [comment]
Try this - [Splash Screen #2 comment](https://github.com/mgks/Android-SmartWebView/issues/2#issuecomment-283334265)
this might help you.
